### ISSUE TITLE
Fehlerausgabe

### ISSUE THREAD

**Issue by julianUni** [sclab2015/sclab_ws1#1]
Bennenung und Zuordnung der Fehlerwerte an Aufgabentext anpassen!
Anmerkung von Robert: nicht einzeln, sondern als Tabelle ausgeben (Format exakt wie auf Blatt gefordert).

**Comment by gueraf** [comment]
Kümmerst du dich darum?

**Comment by julianUni** [comment]
komme erst heute Abend dazu, aber dann kann ichs machen.

**Comment by gueraf** [comment]
Vielen Dank. Kannst du auch einen Blick auf das andere Problem werfen (Intervall nicht durch dt teilbar) und dann submitten? Ich kann morgen in der Früh (in acht Stunden) kurz einen Blick drauf werfen, sitze dann aber bis Montag 15:30 eurer Zeit im Flugzeug. Submittest du dann am Montag? Danke.

**Comment by gueraf** [comment]
Bitte "git pull" ausführen bevor du anfängst zu arbeiten. Denke ansonsten sieht der Code recht gut aus. Habe die Main nicht wirklich durchgearbeitet, Ergebnis sieht aber gut aus. Bitte schau nochmal auf meinen Code. Wie gesagt, ich bin arg übermüdet.

**Comment by julianUni** [comment]
Alle Fehler werden ausgegeben und Bennenung ist klar.
