### ISSUE TITLE
t0 nicht explizit erwähnt; Reihenfolge der Argumente

### ISSUE THREAD

**Issue by gueraf** [sclab2015/sclab_ws1#4]
In der Angabe wird t0 nicht erwähnt, ich denke die nehmen implizit 0 an. Sollten wir das auch noch ändern?

Sollen wir die Reihenfolge der Argumente zu f, y0, dt, (t0,) t_end ändern?

**Comment by julianUni** [comment]
Wir behalten t0, das macht den code weniger eingeschränkt.
Reihenfolge zu ändern finde ich überflüssig, ist so auch verständlich.
